source("readData.R")
baltimore <- subset(NEI, fips == "24510")
aggregated <- aggregate(baltimore$Emissions, by=list(year=baltimore$year, type=baltimore$type), FUN=sum)
ggplot(aggregated, aes(year, x)) + geom_line() + facet_grid(. ~ type) + ylab("Total emissions")
ggsave(filename="plot3.png")